trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: SonarCloudPrepare@3
    displayName: 'SonarQube: Prepare'
    inputs:
      SonarQube: 'SonarQubeCloud'
      organization: 'ltheobald'
      scannerMode: 'Other'

  - task: JavaToolInstaller@0
    displayName: 'Install Java 21'
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@4
    displayName: 'Maven Build'
    inputs:
      mavenPomFile: 'pom.xml'
      options: >
        -DnvdApiKey=4a0670ba-15a8-47c7-a327-a3e9d54df86b
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean verify sonar:sonar package'

  - task: SonarCloudAnalyze@3
    displayName: 'SonarQube: Analyze'

  - task: SonarCloudPublish@3
    displayName: 'SonarQube: Publish'
    inputs:
      pollingTimeoutSec: '300'
