trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  mavenRootFolder: $(Pipeline.Workspace)/.m2/
  mavenCacheFolder: $(mavenRootFolder}repository

steps:
  - task: SonarCloudPrepare@3
    displayName: 'SonarQube: Prepare'
    inputs:
      SonarQube: 'SonarQubeCloud'
      organization: 'ltheobald'
      scannerMode: 'Other'

  - task: JavaToolInstaller@0
    displayName: 'Install Java 21'
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  # Set up Maven to use the custom cache path
  - script: |
      mkdir -p ~/.m2
      echo "<settings><localRepository>$(mavenCacheFolder)</localRepository></settings>" > $(mavenRootFolder}settings.xml
    displayName: 'Prepare Maven local repo'

  # Cache Maven dependencies
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
      path: $(mavenCacheFolder)
  - task: Maven@4
    displayName: 'Maven Build'
    inputs:
      mavenPomFile: 'pom.xml'
      options: >
        -DnvdApiKey=$(NVD_API_KEY)
        -Dsonar.projectKey=LTheobald_kafka-testbed
        --settings $(mavenRootFolder}settings.xml
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean verify sonar:sonar package'

  - task: SonarCloudAnalyze@3
    displayName: 'SonarQube: Analyze'

  - task: SonarCloudPublish@3
    displayName: 'SonarQube: Publish'
    inputs:
      pollingTimeoutSec: '300'