spring:
  docker:
    compose:
      enabled: true

  # Keeping dev active by default
  profiles:
    active: dev

  # Kafka
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: my-group
      properties:
        specific.avro.reader: true

  # JPA & Datasource (PostgreSQL)
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration