logging:
  level:
    org.springframework.boot.docker.compose: DEBUG

spring:
  # Kafka
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        schema.registry.url: http://localhost:8085
    consumer:
      properties:
        schema.registry.url: http://localhost:8085

  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_testbed
    username: read_only_user
    password: Read_0nly_password